name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [pybind11-exp-add-ingest]

defaults:
  run:
    shell: bash

jobs:
  test_runner:
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Ensure latest rocksdb
      run: |
        echo `pwd`
        cd lib/rocksdb
        git checkout master
        git pull
        cd ../..
    - name: Install libraries
      run: |
        sudo apt-get install -y \
          cmake \
          libgflags-dev libsnappy-dev liblz4-dev libzstd-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8 pytest
    - name: Install pyrocksdb
      run: |
        python setup.py install
    - name: Run tests
      run: pytest
